project:
  type: website

website:
  title: "Resources"
  navbar:
    logo: /img/LOGOx2-white.png
    left:
      - href: index.qmd
        text: Home
      - text: Training materials
        menu:
          - resources.qmd
          - module1a/module1a_overview.qmd
          - module1b/module1b_overview.qmd
          - module3c/module3c_overview.qmd
          - module3d/module3d_overview.qmd
          - dataviz/dataviz.qmd
      - href: curriculum.qmd
        text: Curriculum
  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: github
        href: https://github.com/WCSCourses
      - icon: twitter 
        href: https://twitter.com/t3connect

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - section: "Module 1A"
        contents:
          - module1a/module1a_introduction.qmd
          - module1a/module1a_strategies.qmd
          - module1a/module1a_elements.qmd
          - module1a/module1a_training_design.qmd
      - section: "Module 1B"
        contents:
          - module1b/module1b_introduction.qmd
          - module1b/module1b_ethical_issues.qmd
          - module1b/module1b_flow_of_data.qmd
          - module1b/module1b_implementing_genomics_in_healthcare.qmd
          - module1b/module1b_infrastructure.qmd
          - module1b/module1b_microbial_genomics_resources.qmd
      - section: "Module 3C"
        contents:
          - module3c/module3c_introduction.qmd
          - module3c/module3c_activities_background.qmd
          - module3c/module3c_activity1a.qmd
          - module3c/module3c_activity1b.qmd
          - module3c/module3c_activity1c.qmd
          - module3c/module3c_activity1d.qmd
          - module3c/module3c_activity1e.qmd
          - module3c/module3c_activity2.qmd
          - module3c/module3c_activity3.qmd
          - module3c/module3c_bonus.qmd
          - module3c/module3c_resources.qmd
      - section: "Module 3D"
        contents:
          - module3d/module3d_introduction.qmd
          - module3d/module3d_group_activity.qmd
          - module3d/module3d_resources.qmd
      - section: "Data viz"
        contents:
          - dataviz/dataviz.qmd
          - dataviz/dataviz_groupactivity.qmd
          - dataviz/dataviz_Microreact_demo.qmd
          - dataviz/dataviz_Microreact_activity.qmd
          
format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true

