project:
  type: website

website:
  title: "WCS Resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Courses
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About Us

  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto
  

