project:
  type: website

website:
  title: "Resources"
  navbar:
    logo: /img/LOGOx2-white.png
    left:
      - href: index.qmd
        text: Home
      - text: Resources
        menu:
          - resources.qmd
          - dataviz.qmd
      - href: about.qmd
        text: About Us
  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: github
        href: https://github.com/WCSCourses
      - icon: twitter 
        href: https://twitter.com/t3connect

  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true

