---
title: "Quiz on adult learning"
---

This quiz should help learners to self-assess whether they have understood all the material so far. If there is something they are not sure about, they can revisit the earlier steps and retake the quiz i. The result of the quiz does not affect your progress on this course in any way.

The methods and practice of teaching adults are called:\
a. Andralogy b. Analogy c. Andragogy d. Pedagogy

According to adult learning principles, adult learners are:

a\. Self-directed

b\. Self-taught

c\. Self-aware

d\. Self-sufficient

One of the main characteristics of adult learners is that they:

a\. Don't need to learn much

b\. Have a vast array of experiences to build upon

c\. Like the job they do

d\. Are financially stable

One of the main motivating factors for an adult learner is:

a\. Satisfying curiosity

b\. Problem solving

c\. Passing the time

d\. Meeting other people

Adult learners would like to see the immediate application of their newly acquired knowledge or skills: 

a\. Sometimes

b\. Rarely

c\. Mostly

d\. Almost never 
