---
title: "Introduction"
---

#### **Overview of adult learning principles and training design techniques**

*This module was made available to participants through a Learning Management System, before the actual face-to-face course.*

*The forums created an opportunity for learners to reflect and also to communicate their thoughts to instructors and to their peers.*

**What this module covers:**

This introductory module gives learners a chance to explore their own memories and habits regarding learning and training. 

It also explains educational theory that underpins adult teaching and training, and the approaches the educators used for this particular course.The module presents an approach to training design which will be used throughout the course, including in the course project when learners design training on their own.

**Intended learning outcomes** for this module

At the end of the module, learners should be able to: 

\-  List main principles underpinning adult learning 

\-  Describe practical application of adult learning principles 

\-  Explain outcome driven design approach for use in training and teaching 

\-  Define learning outcomes in a SMART way using Bloom's taxonomy

 - Discuss purpose, scope and types of evaluation in education

\-  Plan their training design required for the course project.  

This module takes approximately 2 hours to go through. 

#### Forum: **Icebreaker activity**

In this forum, learners are asked to share a few lines about themselves.

-   What they do

-   Where they are from

-   Something they do well (why do they think that's the case?)

-   Something they do not do well (why do they think that's the case?)

#### **Forum: What are your learning and teaching experiences?**

In this forum, learners are asked to share

-   Their happiest memory of learning.

-   What experience they remember as being most fun, most effective, and perhaps most influential?

-   Their happiest memory of teaching or training.

-   What experience they remember as being most fun, most effective, and perhaps most influential ?

-   Do they teach or train the way they like to learn? Why? or Why not?
