---
title: "Introduction"
---

## **Introduction to module 4**

In this final module, you will have a chance to put into practice what you have learned earlier in the course. You will spend most of the day on Wednesday working on a design for your own training. There will be some short guided exercises throughout the day to help you to think about specific aspects such as evaluation, public speaking and so on. 

On Thursday, you will have an opportunity to present a summary of your design to the rest of the group. You will receive peer feedback on your design as well as commenting on designs by your fellow learners.

You probably won't be able to complete an entire detailed design for a training activity in just one day, so please don't worry if you run out of time! The idea is that you will be able to start thinking about the key questions and have the core of something you can take forward for further development after the course finishes.

# **Learning Outcomes**

At the end of this module participants will be able to:

• Define the appropriate context for a training activity

• Apply learning theory from earlier modules to design a training activity

• Create an outline plan for the chosen training activity

• Present plans to other learners and give and receive feedback on proposed activities
